[package]
name = "speedreader"
version = "0.1.0"
edition = "2024"

[dependencies]
cli-clipboard = "0.4.0"
directories = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
